//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inf04_02_24._06_SG.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inf04_02_24._06_SG.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gorillaz
        ///&quot;The Now Now&quot;
        ///11
        ///2018
        ///11000102
        ///
        ///My Chemical Romance
        ///&quot;The Black Parade&quot;
        ///14
        ///2006
        ///304666444
        ///
        ///Wilki
        ///&quot;wilki&quot;
        ///16
        ///1992
        ///4000230
        ///
        ///30 Seconds To Mars
        ///&quot;A Beautiful Lie&quot;
        ///13
        ///2009
        ///300120222
        ///
        ///30 Seconds To Mars
        ///&quot;This Is War&quot;
        ///15
        ///2009
        ///22000000
        ///
        ///Melanie Martinez
        ///&quot;Cry Baby&quot;
        ///16
        ///2015
        ///400345042
        ///
        ///The Rasmus
        ///&quot;Dead Letters&quot;
        ///10
        ///2003
        ///253453
        ///
        ///Metallica
        ///&quot;Metallica&quot;
        ///12
        ///1991
        ///1506404300
        ///
        ///Meskie Granie Orkiestra 2022
        ///&quot;Meskie Granie 2022&quot;
        ///30
        ///2022
        ///243085
        ///
        ///Krzysztof Zalewski
        ///&quot;Zlo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obraz {
            get {
                object obj = ResourceManager.GetObject("obraz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obraz2 {
            get {
                object obj = ResourceManager.GetObject("obraz2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap obraz3 {
            get {
                object obj = ResourceManager.GetObject("obraz3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
